### ISSUE TITLE
processing traditional format, encountered error in blech_clust and blech_common_average_reference

### ISSUE THREAD

**Issue by emmalala123** [katzlabbrandeis/blech_clust#263]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Getting trial markers from digital inputs
Traceback (most recent call last):
  File "blech_clust.py", line 440, in <module>
    dig_in_array = hdf5_handler.get_digital_inputs(sampling_rate)
  File "blech_clust.py", line 137, in get_digital_inputs
    return np.stack(dig_in_list)
  File "<__array_function__ internals>", line 5, in stack
  File "/home/cmazzio/anaconda3/envs/blech_clust/lib/python3.8/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

Not sure if they are related, but after the above error was thrown, this function would not run and threw this error.
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$ python blech_common_avg_reference.py $DIR
Traceback (most recent call last):
  File "blech_common_avg_reference.py", line 73, in <module>
    this_pipeline_check.check_previous(script_path)
  File "/home/cmazzio/Desktop/blech_clust/utils/blech_utils.py", line 110, in check_previous
    raise ValueError(f'Parent script [{parent_script}] not found in log')
ValueError: Parent script [['/home/cmazzio/Desktop/blech_clust/blech_clust.py']] not found in log
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$

**Comment by abuzarmahmood** [comment]
The second error is intentional. There is new functionality to not run downstream scripts if upstream ones haven't completed successfully. You can check which ones were `attempted` and `successful` by looking at the `execution_log.json` in the data_dir.

For the first error, can you confirm that when you ran `blech_clust.py` , it printed some like, `Traditional file format detected`, and then printed something like

```
check_str = f"""                                                                                                    
== Amplifier channels: \n{amp_channel_names}\n                                                                      
== Digital input channels: \n{dig_in_channels}\n                                                                    
== Sampling rate: {sampling_rate} Hz\n                                                                              
== Ports: {ports}\n    
```

This is before the part with the error so should have been printed. Just want to make sure there are no other issues with detecting the format.

**Comment by abuzarmahmood** [comment]
@emmalala123 is this still an issue?
If not, I will go ahead and close

**Comment by emmalala123** [comment]
I don’t think it’s a problem anymore, sorry for not closing the issue.

Best,
Emma
