### ISSUE TITLE
strange formatting on blech_post_process.py, input acts weirdly.

### ISSUE THREAD

**Issue by emmalala123** [katzlabbrandeis/blech_clust#288]
Here is what I mean:

```
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$ python blech_post_process.py $DIR
============================================================
Attempting blech_post_process.py, started at 2024-12-18 14:47:06
============================================================
==============================
Removing raw recordings from hdf5 file

Raw recordings have already been removed, so moving on ..
==============================
==============================
Cleaning memory monitor data

==============================

==== Manual Post-Processing ====



 Electrode number :: "x" to exit :: Please enter an interger
3
3   

 Electrode number :: "x" to exit ::  Solution number :: "x" to exit ::  Cluster numbers (anything separated) ::"x" to exit :: ||| Electrode 3, Solution 3, Cluster [] |||
^C SPLIT this cluster? (y/n)"x" to exit :: Traceback (most recent call last):
  File "blech_post_process.py", line 215, in <module>
    this_split_merge_signal = post_utils.split_merge_signal(
  File "/home/cmazzio/Desktop/blech_clust/utils/blech_post_process_utils.py", line 985, in __init__
    self.ask_split()
  File "/home/cmazzio/Desktop/blech_clust/utils/blech_post_process_utils.py", line 998, in ask_split
    msg, continue_bool = entry_checker(\
  File "/home/cmazzio/Desktop/blech_clust/utils/blech_utils.py", line 179, in entry_checker
    msg_input = input(msg.join([' ',exit_str]))
KeyboardInterrupt
Closing remaining open files:/media/cmazzio/storage/eb_ephys/cue_onset_eb27_behandephys_12_10_24_241210_123228/cue_onset_eb27_behandephys_12_10_24_241210_123228_repacked.h5...done

(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$ python blech_post_process.py $DIR
============================================================
Attempting blech_post_process.py, started at 2024-12-18 14:47:55
============================================================
==============================
Removing raw recordings from hdf5 file

Raw recordings have already been removed, so moving on ..
==============================
==============================
Cleaning memory monitor data

==============================

==== Manual Post-Processing ====



 Electrode number :: "x" to exit :: Please enter an interger
3
3
0
 Electrode number :: "x" to exit ::  Solution number :: "x" to exit ::  Cluster numbers (anything separated) ::"x" to exit :: ||| Electrode 3, Solution 3, Cluster [0] |||

 SPLIT this cluster? (y/n)"x" to exit :: Please enter (y/n)
n

 SPLIT this cluster? (y/n)"x" to exit ::  Single-unit? (y/n)"x" to exit :: Please enter (y/n)
y
r
 Single-unit? (y/n)"x" to exit ::  Regular or fast spiking? (r/f)"x" to exit :: Adding new unit unit000
==== unit000 Complete ===

==== Iteration Ended ===


==== Manual Post-Processing ====

```

**Comment by abuzarmahmood** [comment]
Should be fixed now.
If issue persists, please reopen issue.
