### ISSUE TITLE
blech_units_characteristics.py erroring 

### ISSUE THREAD

**Issue by emmalala123** [katzlabbrandeis/blech_clust#290]
Here I'm going to include from blech_make_arrays.py, just for context. I think that everything  but unit characteristics ran fine.

```
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$ python blech_make_arrays.py $DIR
============================================================
Attempting blech_make_arrays.py, started at 2024-12-19 11:46:26
============================================================
Processing: /media/cmazzio/storage/eb_ephys/cue_onset_eb27_behandephys_12_10_24_241210_123228/
Taste dig_ins ::: 
dig_in_14
dig_in_15
dig_in_16

Laser dig_in ::: 
None

=====================
Correcting laser timing using info_dict
Assuming only 1 laser condition
=====================
=== No trials were cutoff ===
Using durations ::: [2000, 5000]
Sorted units found ==> Making spike trains
Creating spike-trains for dig_in_14
Creating spike-trains for dig_in_15
Creating spike-trains for dig_in_16
No EMG Data Found...NOT MAKING EMG ARRAYS
============================================================
Completed blech_make_arrays.py, ended at 2024-12-19 11:46:31
============================================================
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$ bash blech_run_QA.sh $DIR

==============================
Running QA tests on Blech data
Directory: /media/cmazzio/storage/eb_ephys/cue_onset_eb27_behandephys_12_10_24_241210_123228

Running Similarity test
============================================================
Attempting unit_similarity.py, started at 2024-12-19 11:46:45
============================================================
Processing : /media/cmazzio/storage/eb_ephys/cue_onset_eb27_behandephys_12_10_24_241210_123228/
==================
Similarity calculation starting
Similarity cutoff ::: 50
17it [00:01, 14.06it/s]
Similarity calculation complete, results being saved to file
==================
============================================================
Completed unit_similarity.py, ended at 2024-12-19 11:46:46
============================================================

Running Drift test
============================================================
Attempting drift_check.py, started at 2024-12-19 11:46:51
============================================================
Processing : /media/cmazzio/storage/eb_ephys/cue_onset_eb27_behandephys_12_10_24_241210_123228/
Uneven # of stimulus presentations: filling with NaN
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
No spikes found, getting spikes ...
Loading spikes
Spike trains loaded from following dig-ins
0. /spike_trains/dig_in_14 (Group) ''
1. /spike_trains/dig_in_15 (Group) ''
2. /spike_trains/dig_in_16 (Group) ''
No firing rate params found...using default firing params
{'baks_dt': 0.001,
 'baks_resolution': 0.025,
 'dt': 1,
 'step_size': 25,
 'type': 'conv',
 'window_size': 250}
If you want specific firing params, set them manually
Uneven numbers of trials...not stacking into firing rates array
============================================================
Completed drift_check.py, ended at 2024-12-19 11:47:25
============================================================

Finished QA tests
==============================
(blech_clust) cmazzio@cmazzio-Precision-Tower-5810:~/Desktop/blech_clust$  python blech_units_characteristics.py $DIR
/home/cmazzio/anaconda3/envs/blech_clust/lib/python3.8/site-packages/tqdm/std.py:666: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
============================================================
Attempting blech_units_characteristics.py, started at 2024-12-19 12:03:30
============================================================
Loading spikes
Spike trains loaded from following dig-ins
0. /spike_trains/dig_in_14 (Group) ''
1. /spike_trains/dig_in_15 (Group) ''
2. /spike_trains/dig_in_16 (Group) ''
Traceback (most recent call last):
  File "blech_units_characteristics.py", line 73, in <module>
    this_dat.get_sequestered_data()
  File "/home/cmazzio/Desktop/blech_clust/utils/ephys_data/ephys_data.py", line 1065, in get_sequestered_data
    self.get_sequestered_spikes()
  File "/home/cmazzio/Desktop/blech_clust/utils/ephys_data/ephys_data.py", line 1005, in get_sequestered_spikes
    this_seq_spikes = self.spikes[taste_ind][this_row['trial_inds']]
IndexError: list index out of range
```

**Comment by emmalala123** [comment]
ooh, now I see this line "If you want specific firing params, set them manually
Uneven numbers of trials...not stacking into firing rates array"

I think the issue is that I don't know how this is done. I'll ask around

**Comment by abuzarmahmood** [comment]
Can you please include what  commit / branch this is on?

**Comment by abuzarmahmood** [comment]
The issue with the `blech_units_characteristics.py` script is due to an `IndexError` in the `get_sequestered_spikes` method of the `ephys_data` class. This error suggests incorrect indexing of the `self.spikes` list or the `trial_inds` in the `this_row` dictionary. The following suggestions and changes were made to address this:

1. **Check the Indexing:**
   - Ensure that `taste_ind` and `this_row['trial_inds']` are within the valid range of indices for `self.spikes`.
   - Add checks or print statements to verify the values of `taste_ind` and `this_row['trial_inds']` before the indexing operation.

2. **Add Error Handling:**
   - Implement a try-except block around the indexing operation to catch the `IndexError` and provide a more informative error message.

3. **Debugging Information:**
   - Add print statements to log the values of `taste_ind`, `this_row['trial_inds']`, and the length of `self.spikes` to help identify why the index is out of range.

Here is an example modification to the `get_sequestered_spikes` method:

```python
def get_sequestered_spikes(self):
    try:
        this_seq_spikes = self.spikes[taste_ind][this_row['trial_inds']]
        self.sequestered_spikes.append(this_seq_spikes)
    except IndexError as e:
        print(f"IndexError: {e}")
        print(f"taste_ind: {taste_ind}, trial_inds: {this_row['trial_inds']}")
        print(f"Length of spikes: {len(self.spikes)}")
        # Handle the error or re-raise with additional context
        raise
```

These changes aim to identify and resolve the indexing issue in the `get_sequestered_spikes` method.

---
*This response was automatically generated by blech_bot*

**Comment by abuzarmahmood** [comment]
Closing issue...please reopen if problem still persists.
